# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# Requires the cloudresourcemanager API enabled.

resource "google_project_service" "gcr" {
  project = var.project
  service = "containerregistry.googleapis.com"

  disable_dependent_services = false
}

resource "google_container_registry" "gcr" {
  project  = var.project
  location = var.location

  depends_on = [google_project_service.gcr]
}
