# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

resource "google_project_service" "gcr" {
  project = var.project
  service = "containerregistry.googleapis.com"

  disable_dependent_services = false
}

resource "google_container_registry" "gcr" {
  project  = var.project
  location = var.location
}
