# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# variable "labels" {
#   description = "Basic set of labels to be used on any and all supporting resources"
#   type        = map(string)
#   default = {
#     managed   = "Terragrunt"
#     ephemeral = "true"
#   }
# }

variable "project" {
  description = "GCP project"
  type        = string
  default     = ""
}

variable "location" {
  description = "GCP project"
  type        = string
  default     = "US"
}

# variable "region" {
#   description = "GCP project"
#   type        = string
#   default     = "us-east1"
# }

# variable "zone" {
#   description = "GCP project"
#   type        = string
#   default     = "us-east1-c"
# }
